services:
  postgres:
    image: postgres:17.4
    restart: "no"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order-service
volumes:
  postgres_data:
